apiVersion: v1
kind: Service
metadata:
  name: carpeta-ciudadana-frontend
  labels:
    app: carpeta-ciudadana-frontend
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: carpeta-ciudadana-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP

