---
apiVersion: v1
kind: Namespace
metadata:
  name: carpeta-ciudadana
  labels:
    app: carpeta-ciudadana
    component: messaging
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-system
  labels:
    app: rabbitmq-cluster-operator
