apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres-secret
  namespace: carpeta-ciudadana
type: Opaque
data:
  # echo -n 'auth_service_user' | base64
  POSTGRES_USER: YXV0aF9zZXJ2aWNlX3VzZXI=
  # echo -n 'auth_service_password123' | base64  
  POSTGRES_PASSWORD: YXV0aF9zZXJ2aWNlX3Bhc3N3b3JkMTIz
  # echo -n 'auth_service_db' | base64
  POSTGRES_DB: YXV0aF9zZXJ2aWNlX2Ri